name: Sync main branch to personal

on:
  push:
    branches:
      - main   # change to your default branch name if different

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main to personal repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          # Add personal remote using PAT in secret
          git remote add personal "https://x-access-token:${{ secrets.ORG_TO_PERSONAL_SYNC }}@github.com/Digisperts/rebrand.git"
          git push personal main --force
