name: Sync to Personal Repo

on:
  push:
    branches:
      - main   # change this if your default branch is something else

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push to personal repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add personal https://YOUR_USERNAME:${{ secrets.PERSONAL_TOKEN }}@github.com/YOUR_USERNAME/PERSONAL_REPO.git
          git push personal main --force
