name: Sync main branch to personal

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ORG_TO_PERSONAL_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push main to personal repo
        run: |
          git config user.name "Digisperts"
          git config user.email "digisperts@gmail.com"
          git remote add personal git@github.com:Digisperts/rebrand.git
          git push personal main --force
